---

inventory: 
    plugin: NetBoxInventory2 #Can use Netbox and Ansible
    options:
      nb_url: "Netbox URL"
      nb_token: "Netbox Token" #Should use export NB_TOKEN = "YourTokenHere"
      ssl_verify: false
      use_platform_slug: true #Use's built in slugs. Preferred method
      #filter_parameters: {"platform" : "ios"} #Filter through netbox from the cfg.file

runner:
   plugin: threaded #Serial will not use concurrent
   options:
      num_workers: 4 #How many threads will work with devices