#!/usr/bin/env python3
"""Write ``bunnyauto.yaml`` for CI from environment variables.

``bunnyauto.yaml`` is gitignored (it holds the real NetBox URLs), so CI
generates it. URLs come from GitHub repo *Variables*; tokens stay in *Secrets*
and are read by bunnyauto itself at runtime, not written here.

Required env vars:
  BUNNYAUTO_TEST_NB_URL   BUNNYAUTO_PROD_NB_URL
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

TEMPLATE = """\
# Generated by scripts/ci_write_env_file.py — do not edit.
environments:
  test:
    nb_url: {test_url}
    default_tag: nornirtest
    token_env: BUNNYAUTO_TEST_NB_TOKEN
  prod:
    nb_url: {prod_url}
    default_tag: networking-active
    token_env: BUNNYAUTO_PROD_NB_TOKEN
    protected: true
"""


def main() -> int:
    test_url = os.environ.get("BUNNYAUTO_TEST_NB_URL", "").strip()
    prod_url = os.environ.get("BUNNYAUTO_PROD_NB_URL", "").strip()
    missing = [
        name
        for name, value in (
            ("BUNNYAUTO_TEST_NB_URL", test_url),
            ("BUNNYAUTO_PROD_NB_URL", prod_url),
        )
        if not value
    ]
    if missing:
        print(f"ci_write_env_file: missing variable(s): {', '.join(missing)}", file=sys.stderr)
        return 1

    Path("bunnyauto.yaml").write_text(
        TEMPLATE.format(test_url=test_url, prod_url=prod_url), encoding="utf-8"
    )
    print("wrote bunnyauto.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main())
